version: '3'
services:
  aurora-postgres:
    platform: linux/amd64
    image: postgres:12-bullseye
    restart: on-failure
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=aurora
    ports:
      - "5432:5432"
    volumes:
      - "aurora-db-data:/var/lib/postgresql/data"

  aurora:
    platform: linux/amd64
    depends_on:
      - aurora-postgres
    build:
      # set build context to the root directory of the go monorepo
      context: ../../../
      args: 
         HCNET_CORE_VERSION: ${HCNET_CORE_VERSION:-}
      dockerfile: services/aurora/docker/Dockerfile.dev
    restart: on-failure
    ports:
      - "8000:8000"
      - "11725:11725"
    environment:
      - DATABASE_URL=postgres://postgres@host.docker.internal:5432/aurora?sslmode=disable
      - NETWORK=testnet
      - PER_HOUR_RATE_LIMIT=0
    command: ["--apply-migrations"]
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  aurora-db-data:
