name: Aurora master

on:
  push:
    branches: [master]

jobs:

  push-state-diff-image:
    name: Push hcnet/ledger-state-diff:{sha,latest} to DockerHub
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@bb984efc561711aaa26e433c32c3521176eae55b
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to DockerHub
        uses: docker/build-push-action@7f9d37fa544684fb73bfe4835ed7214c255ce02b
        with:
          push: true
          tags: hcnet/ledger-state-diff:${{ github.sha }},hcnet/ledger-state-diff:latest
          file: exp/tools/dump-ledger-state/Dockerfile
          build-args: GITCOMMIT=${{ github.sha }}
          no-cache: true
